name: Atualizar Atividade Recente

on:
  schedule:
    - cron: "0 * * * *" # Executa a cada hora
  workflow_dispatch:

jobs:
  update-readme:
    name: Atualiza README.md com atividade recente
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessário para escrever no README.md
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
